# Rules in format: ApiClass = DaoClass : apiField=daoField, ...
CreateUserResponse = UserDao : username=username,role=role,id=id,name=name
CreateAccountResponse = AccountDao : accountNumber=accountNumber,balance=balance,id=id
ChangeNameResponseModel = UserDao : name=name

# C2C transfer response mapping
C2CResponseModel = TransactionDao : amount=amount,senderAccountId=senderAccountId,receiverAccountId=receiverAccountId