### Positive case: Deposit to account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTc6S2F0ZTE5OTck

{
  "id": 1,
  "balance": 100
}

### Negative case: Deposit to account 0 amount
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTc6S2F0ZTE5OTck'

{
  "id": 1,
  "balance": 0
}

### Negative case: Deposit to account negative amount
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTc6S2F0ZTE5OTck'

{
  "id": 1,
  "balance": -100
}

### Positive case: Transfer money C2C
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTc6S2F0ZTE5OTck'

{
  "senderAccountId": 2,
  "receiverAccountId": 1,
  "amount": 50
}

### Negative case: Transfer money C2C to not existing client
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTc6S2F0ZTE5OTck'

{
  "senderAccountId": 1,
  "receiverAccountId": 999,
  "amount": 50
}

### Negative case: Transfer money C2C from not existing client
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTc6S2F0ZTE5OTck'

{
  "senderAccountId": 999,
  "receiverAccountId": 2,
  "amount": 50
}

### Negative case: Transfer money Me2Me
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTc6S2F0ZTE5OTck'

{
  "senderAccountId": 1,
  "receiverAccountId": 1,
  "amount": 50
}

### Positive case: Change username
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTc6S2F0ZTE5OTck'

{
  "name" : "New Name"
}

### Negative case: Change username to blank
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTc6S2F0ZTE5OTck'

{
  "name" : " "
}

### Negative case: Change below character limit
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTc6S2F0ZTE5OTck'

{
  "name" : "ab"
}

### Negative case: Change username above character limit
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTc6S2F0ZTE5OTck'

{
  "name" : "sijdncvsijdcvnsvbnhvbndfvnfhvbnevhbn"
}

### Negative case: Change username on high character limit
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTc6S2F0ZTE5OTck'

{
  "name" : "aaaaaaaaaaaaaaa"
}

### Negative case: Change username on low character limit
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTc6S2F0ZTE5OTck'

{
  "name" : "aaa"
}

### Negative case: Change username to special symbols "$%&&$%"
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTc6S2F0ZTE5OTck'

{
  "name" : "$%&&$%"
}



